### ISSUE TITLE
product page - images visual segment

### ISSUE THREAD

**Issue by mrhut10** [mrhut10/futuresFineFurniture#29]
with Tailwind @lukebennett88 
how can we add a very slight dropshaddow or border in tailwind to provide a visual segment / division so that the user can see why the text content is getting broken up??   On productpage

see example picture below.

<img width="540" alt="needs visual segment for eyes" src="https://user-images.githubusercontent.com/20330237/55302847-e2e10e00-548e-11e9-82fb-9abdeec24685.PNG">

**Comment by mrhut10** [comment]
I justed reliesed this is a bug from my merging conflicts,
the content is getting displayed twice.

My bad, fixed in local commit which i'll push now,

also i'll close this request.

@lukebennett88 i'll learn tailwind dropshadows later on

**Comment by lukebennett88** [comment]
OK cool, I was thinking that I floated the image to the right to prevent the ugly wrapping.
I can add a subtle shadow and/or border if you like as well, but I think it's probably unnecessary.
