### ISSUE TITLE
related products title doesn't clear fix from product image

### ISSUE THREAD

**Issue by mrhut10** [mrhut10/futuresFineFurniture#43]
the new related Products section, at times the heading doesn't clear fix away from the main product image.
see screenshoot below
<img width="367" alt="Capture" src="https://user-images.githubusercontent.com/20330237/60315417-d72bb780-99a9-11e9-9aaa-d44532588df8.PNG">

if you've got a moment you'd be able to address heaps quicker than i can @lukebennett88 and that would allow me to move on to making a bunch of new routes that display all products within each range so i can have a see more from range link within the related product section.

:)

**Comment by lukebennett88** [comment]
@mrhut10 sure thing mate, happy to take a look.

**Comment by mrhut10** [comment]
Thank you @lukebennett88 make sure you tag me on any issue you need a hand on also !!!! :)

**Comment by mrhut10** [comment]
I spent a few nights cleaning up the source code also, so hopefully it is sightly less spaghetti code :)
just componentized a lot of stuff where i had too much logic within the same file.
@lukebennett88

**Comment by lukebennett88** [comment]
Awesome, makes it so much easier to navigate and understand when everything is organised nicely and broken into smaller components, especially when you're working on someone else's project 😉

Just about to send a PR now, should have everything looking a bit nicer.
@mrhut10

**Comment by mrhut10** [comment]
Amen!! yeah, plus i have a feeling comming back to a project after a week or two sometimes may as well be someone elses project, lol. and thank you again @lukebennett88 
hope your day in the office is going well.

**Comment by mrhut10** [comment]
closing @lukebennett88 PR #44 resolved.
