### ISSUE TITLE
Need to update to Tailwind 1.0

### ISSUE THREAD

**Issue by lukebennett88** [mrhut10/futuresFineFurniture#46]
This website is currently styled with an older version of Tailwind that has some different class names and doesn't have some of the nicer features of 1.0 (such as the new config file.)

I plan to update it when I have some free time, but there is a fair bit of work involved <https://tailwindcss.com/docs/upgrading-to-v1> so this may take me a while.

I might use this as an opportunity to clean up the design a little further if that's OK with you @mrhut10?

**Comment by lukebennett88** [comment]
Started redesigning the site a little last night. Moving away from the colder grays and focusing on the warmer maroon and cream colours.

![screencapture](https://user-images.githubusercontent.com/3422401/60373866-2246d880-9a45-11e9-8cc8-5905b4339a90.png)

I think the site could use a bit more personality with a custom font as well, but the logo is already super busy with 3 different fonts, plus the system font so 4 in total which is too many.
Any idea what font is used for the text that says "Highest Quality Lowest Prices!" in the logo? I don't recognise it, thought it might work well for headings.

**Comment by mrhut10** [comment]
Sorry for delay, with short days I've limited house battery power/juice.

That looks really awesome btw!!
I wasn't able to find the fonts at all originally.

A local sign writer made them when a can got painted, I got hold of the pdf proffs of the artwork and managed to convert to svg straight from the pdfs. And unfortunately they aren't text inside the svg just lines and curves :(

I could try next week to get the font however I think we have a lot of liberty to redesigning as long as we get him to look at before push live.

I should start reading the trail wind docs in the week so I can keep up.

Anything on your end you want a hand with also @lukebennett88 ?

**Comment by lukebennett88** [comment]
Spent a bit more time on it today, starting to look a bit better: 
https://vigilant-fermat-520805.netlify.com/

I might have a play with the logo as well if that’s the case, keep the colours and the word ‘Futures’ and redo the rest — I’ll see how I go anyway.

I’ve also tried to componentise things a bit more and renamed a few things for consistency, so the PR might be a bit of a mess to wade through 😬

On my end, I’m pretty up to date, finishing off a Shopify website at the moment, but hopefully should start on a few new projects next week — will let you know if I need a hand with anything.

@mrhut10

**Comment by mrhut10** [comment]
@lukebennett88 let me know if your happy to resolve this issue after merged #48 & #47

**Comment by lukebennett88** [comment]
Looks good, I'll close this issue. 
Took a minute for the offline plugin to update, so saw the old site at first 😂 
Any other issues like logo or font update, I'll add to another issue.
