### ISSUE TITLE
Better categorise furniture

### ISSUE THREAD

**Issue by lukebennett88** [mrhut10/futuresFineFurniture#56]
This is probably a lot of work, but would greatly improve the navigation of the site.
I think we should break the furniture categories up into further sub-categories e.g: 
- Bedding
  - Bed frames
  - Tallboys
  - Bedside tables
- Dining
  - Dining tables
  - Dining chairs
  - Hall tables

etc.

We should probably include this in the site navigation (again similar to [Zanui](https://www.zanui.com.au) like I mentioned in #55), as well as being able to access the sub categories from the higher level categories (e.g. from the Bedroom section we can have links at the top to `/bedding/bed-frames` or you can scroll down and see everything under bedding like you can at the moment.

Another way to do it is to create a sidebar with filters, we could even do things like sort by colour or brand. Again, a lot of work, writing all the logic and adding all the extra metadata, but would greatly improve the navigation of the site, plus it would be a good challenge 😜

Let me know what you think @mrhut10

**Comment by mrhut10** [comment]
this had been on my mind a while ago, I only deleted a little bit of code in last week i had put in to help support this future feature. i had a field in product categories called parent.

It certainly is a fairly heavy feature to code, but if we are going to do it, sooner is better than later.

The other advantage which the extra meta data is that we can build a recomendation engine. 
for example, below a product your looking at we currently show others in the range, we could also display a few other similar products. i.e you might be interested in these other dining tables. a recommendation engine is likely more important than the navigation of subcategories but could potentially do both.

that being said the filter idea i suspect would be interesting as would be an extra feature that doesn't need to change any of the current category logic.

I might mud map out few idea's on paper.

**Comment by mrhut10** [comment]
this issue is now addressed within the wider scope of #62 

as the new schema now supports subcategories :)

so seeing a product can be attached to a child category we will get to do some data tree walking to find all children products of a parent category which should be a fun implementation :)
