### ISSUE TITLE
Sanity.io migration for backend

### ISSUE THREAD

**Issue by mrhut10** [mrhut10/futuresFineFurniture#62]
now that I've built the backend and schema see #58 

try ```npm run dev``` or ```npm run dev-web``` to play with.
(you'll likely need a login which i can give you)

we need to
- have website pull in data from sanity rather than the current markdown file based backend.
- transfer the approx 240 products into sanity.io

**Comment by mrhut10** [comment]
I wont start implimenting pulling data from sanity tonight i must spend a little time on this assignment that is due sunday night :(

but early in the new week i should be able to start addressing this :)

**Comment by mrhut10** [comment]
ok, been two weeks i think sense i got to look at this.

i've now made a export script, and have one my first imput of 256 products yay!!!
@lukebennett88 what a win.

however wasn't perfect, will need to put category, images feilds in manually.

but that shouldn't take me too long.

once i do that, it will be a case of using this new data on the front end of the webpage

**Comment by mrhut10** [comment]
i didn't mean to remove the milestone?  :(

milestone still active

**Comment by lukebennett88** [comment]
Glad to hear it's going well 😊

**Comment by mrhut10** [comment]
just an update on this,

making great progress, still main website using old database, however the temporary routes is holding all of the products from the new database

https://www.futuresfinefurnitureandbedding.com/sanity-range/

which i'll migrate to the old route of 
https://www.futuresfinefurnitureandbedding.com/range/

once I've made sure all of the products are there.

so far so good.

**Comment by mrhut10** [comment]
most of my import file worked however i misunderstood how relationship fields worked, how as a result i'm not manually telling sanity what category and range each product is in, a little time consuming but will only need to do it once.

**Comment by mrhut10** [comment]
all working under branch moveToNewDatabase
I'll ask a few family to test the site but believe all working so can finally close this off.

**Comment by mrhut10** [comment]
if you wanted to have a quick play @lukebennett88 or anyone else
its live on
https://staging.futuresfinefurnitureandbedding.com/

unless i find any major problems i expect I'll push live to main domain some point today.

**Comment by lukebennett88** [comment]
Hey Alistair 👋
Happy New Year!
Looks like the Markdown isn't getting parsed properly — I'm still seeing asterisks instead of bullets etc.
There is also a `gatsby-image` fragment for Sanity: https://www.gatsbyjs.org/packages/gatsby-image/#gatsby-source-sanity
Might be worth implementing to improve the load speed?
I've got a few UI improvements in mind as well, so if I get a change I'll send you another PR.
Apart from that though, the functionality of the site seems to be working as before.

**Comment by mrhut10** [comment]
Hay Happy new year too!!!!
should really catchup, have some exciting news, i'll PM you in a tick.
yeah i'll look at the gatsby-image for sanity would be great.

also yeah the dot points i'll make a fix on in a bit.

I tried to make the Latest Specials on a carosel but is a nightmare to make look good on mobiles so decided wasn't needed.

really hope can catchup shortly too!!!

**Comment by lukebennett88** [comment]
I've done a few carousels now 😜
If I get a chance I'll do a PR with a few visual changes and have a go at implementing a carousel as well.
Now that the site is sourcing from Sanity, will I have any issues doing that? You'll likely have environment variables set up with API keys right?

And super keen to catch up soon! Hope everything is well with you and the family.
New baby soon, how exciting!

**Comment by mrhut10** [comment]
yeah don't stress about the carousel for the specials,
when we do have a stab at it i should priorities enabling a carousel on the product page's to display multiple images for each product. the database was set up with this in mind, just not currently built into the UI, and yeah!! the PM will be about the baby stuff.

and API KEYS, true!!!, i believe I've set the database is public readable, but, it is possible you'll need them. whats the best way to send you a .env file ?

**Comment by mrhut10** [comment]
oh!!!, i should re-implement related products section, I have a quick go at that now.

**Comment by lukebennett88** [comment]
Not sure what the conventional wisdom is when it comes to sharing environment variables.
Probably just send it in Signal?

**Comment by mrhut10** [comment]
ok i've pushed the branch live, just building currently.

**Comment by mrhut10** [comment]
I'll close this, but reopen if build fails
